chore(actions): parallelize builds (#251)

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -43,8 +43,8 @@ jobs:
           filters: |
             validate:
               - '!(README.md|LICENSE|.gitignore|etc/**)'
-  build-and-test:
-    name: Build and test
+  build-and-test-dev:
+    name: Build and test DEV
     needs: [changes]
     if: ${{ needs.changes.outputs.validation-required == 'true' }}
     timeout-minutes: 30
@@ -65,10 +65,6 @@ jobs:
         if: ${{ !vars.QH_DISABLE_CHROME_INSTALL }}
         with:
           chrome-version: stable
-      - name: Build
-        run: |
-          set -x -e -o pipefail
-          mvn -V -e -B -ntp -DskipTests install
       - name: End-to-end Test (Development mode)
         run: |
           set -x -e -o pipefail
@@ -76,6 +72,36 @@ jobs:
       - name: Package test output files (Development mode)
         if: ${{ failure() || success() }}
         run: find . -name surefire-reports -o -name failsafe-reports -o -name selenide-reports | tar -czf tests-reports-dev.tgz -T -
+      - name: Package test output files (Production mode)
+        if: ${{ failure() || success() }}
+        run: find . -name surefire-reports -o -name failsafe-reports -o -name selenide-reports | tar -czf tests-reports-prod.tgz -T -
+      - uses: actions/upload-artifact@v4
+        if: ${{ failure() || success() }}
+        with:
+          name: tests-output-dev
+          path: tests-reports-*.tgz
+  build-and-test-prod:
+    name: Build and test PROD
+    needs: [changes]
+    if: ${{ needs.changes.outputs.validation-required == 'true' }}
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Set up Java
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'temurin'
+          cache: maven
+      - uses: browser-actions/setup-chrome@latest
+        id: setup-chrome
+        if: ${{ !vars.QH_DISABLE_CHROME_INSTALL }}
+        with:
+          chrome-version: stable
       - name: End-to-end Test (Production mode)
         run: |
           set -x -e -o pipefail
@@ -86,5 +112,20 @@ jobs:
       - uses: actions/upload-artifact@v4
         if: ${{ failure() || success() }}
         with:
-          name: tests-output
+          name: tests-output-prod
           path: tests-reports-*.tgz
+  test-results:
+    name: Evaluate Validation Results
+    permissions:
+      issues: read
+      checks: write
+      pull-requests: write
+    if: ${{ always() }}
+    needs: [changes, build-and-test-dev, build-and-test-prod]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set Failure Status
+        if: ${{ always() && (needs.build-and-test-dev.result != 'success' || needs.build-and-test-prod.result != 'success') }}
+        run: |
+          echo "🚫 THERE ARE TEST MODULES WITH FAILURES or BEEN CANCELLED" | tee -a $GITHUB_STEP_SUMMARY
+          exit 1
